############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1


[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
parent = "About"
name = "About Us"
pageRef = "/about"
weight = 1

[[main]]
parent = "About"
name = "Contact"
pageRef = "/contact"
weight = 2

[[main]]
parent = "About"
name = "Markdown Guide"
pageRef = "/elements"
weight = 3

[[main]]
weight = 3
name = "Insights"

[[main]]
weight = 1
parent = "Insights"
name = "Insightz"
pageRef = "/insights"


[[main]]
parent = "Insights"
name = "Author"
pageRef = "/author"

[[main]]
parent = "Insights"
name = "Categories"
pageRef = "/categories"



[[main]]
weight = 4
name = "Resources"

[[main]]
parent = "Resources"
name = "Resources2"
pageRef = "/resources"


[[main]]
parent = "Resources"
name = "Topics"
pageRef = "/topics"

[[main]]
parent = "Resources"
name = "Categories2"
pageRef = "/categories2"


#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
