############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# pageRef = "/"
# weight = 1


[[main]]
name = "About"
pageRef = "/about"
weight = 2

[[main]]
parent = "About"
name = "About Us"
pageRef = "/about"
weight = 1

[[main]]
parent = "About"
name = "Contact Us"
pageRef = "/contact"
weight = 2



[[main]]
weight = 3
name = "Insights"
pageRef = "/insights"

[[main]]
weight = 1
parent = "Insights"
name = "Insights"
identifier = "insightz"
pageRef = "/insights"


[[main]]
parent = "Insights"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Insights"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Insights"
name = "Tags"
pageRef = "/tags"


[[main]]
weight = 4
name = "Resources"
pageRef = "/tools"

[[main]]
weight = 1
parent = "Resources"
identifier = "toolz"
name = "Resources"
pageRef = "/tools"


[[main]]
weight = 2
parent = "Resources"
name = "Topics"
pageRef = "/topics"

[[main]]
weight = 3
parent = "Resources"
name = "Keywords"
pageRef = "/keywords"


#[[main]]
#parent = "Pages"
#name = "404 Page"
#pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Insights"
pageRef = "/insights"
weight = 2

[[footer]]
name = "Resources"
pageRef = "/tools"
weight = 3

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 4
