# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages (main.yml)

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# Also try: git update-index --chmod=+x .github/workflows/main.yml works?!
# Info: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

# ERROR mkdir /resourceCache: permission denied
# Total in 2065 ms
# Error: error building site: render: failed to render pages: render of "404" failed: "/home/runner/work/eoconline.github.io/eoconline.github.io/themes/eoconline/layouts/_default/baseof.html:38:7": execute of template failed: template: 404.en.html:38:7: executing "404.en.html" at <partial "essentials/header.html" .>: error calling partial: "/home/runner/work/eoconline.github.io/eoconline.github.io/themes/eoconline/layouts/partials/essentials/header.html:8:11": execute of template failed: template: partials/essentials/header.html:8:11: executing "partials/essentials/header.html" at <partial "logo">: error calling partial: "/tmp/hugo_cache_runner/modules/filecache/modules/pkg/mod/github.com/gethugothemes/hugo-modules/images@v0.0.0-20240711030223-49ae4a26e064/layouts/partials/logo.html:83:33": execute of template failed: template: partials/logo.html:83:33: executing "partials/logo.html" at <$logo.Resize>: error calling Resize: mkdir /resourceCache: permission denied
# Error: Process completed with exit code 1.

permissions:
  write-all
  #contents: read
  #pages: write
  #id-token: write

# Environment variables available to all jobs and steps in this workflow
env:
  HUGO_ENV: production
  HUGO_VERSION: "0.134.2" # "latest"
  GO_VERSION: "1.22.2"
  NODE_VERSION: "20.0.0"
  TINA_CLIENT_ID: ${{ vars.TINA_CLIENT_ID }}
  TINA_TOKEN: ${{ vars.TINA_TOKEN }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Hugo  (main.yml)
        run: |
          curl -LO "https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz"
          tar -xvf hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz
          sudo mv hugo /usr/local/bin/
          rm hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz
          hugo version

      - name: Install Go (main.yml)
        run: |
          curl -LO "https://dl.google.com/go/go${{ env.GO_VERSION }}.linux-amd64.tar.gz"
          sudo tar -C /usr/local -xzf go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          echo "export PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV
          rm go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          go version

      - name: Setup Project
        run: npm run project-setup

      - name: Install npm dependencies (main.yml)
        run: npm install

      - name: Publish to GitHub Pages (main.yml)
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (main.yml)
        id: deployment
        uses: actions/deploy-pages@v4
